apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: img-db
  name: img-db
spec:
  ports:
    - name: "5465"
      port: 5465
      targetPort: 5432
  selector:
    io.kompose.service: img-db
status:
  loadBalancer: {}
